logo: "/images/prof.jpg?raw=true" # your photo (or logo) here
title: Amanuel Tadiwos # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist and Flutter Developer 
  <br><br>
As a highly skilled data scientist with 2+ years of experience, I am passionate about using data to drive business decisions and improve overall performance. With expertise in statistical analysis, programming languages such as Python and R, and experience with data visualization tools, I am confident in my ability to deliver valuable insights to organizations. 
Additionally, my strong communication skills and ability to work collaboratively make me an asset to any team.   <br><br>
  <a href="https://www.linkedin.com/in/amanuel-tadiwos-607804122/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
